pipeline {
  agent { label 'linux-slave' }

  options {
    skipDefaultCheckout()
  }

  stages {

    stage ('Install dependencies') {
      tools {
        nodejs 'nodejs 8.9.4'
      }
      steps {
        sh '''
          echo "Installing..."
          npm install
          echo "Install dependencies successfully."
          ls -al
        '''
      }
    }
    
    stage ('Test') {
      tools {
        nodejs 'nodejs 8.9.4'
      }
      steps {
        sh 'echo "Run unit test..."'
        sh 'npm test'
        sh 'echo "Run unit test successfully."'
        sh 'ls -al'
      }
    }

    stage ('Build') {
      when {
        branch 'develop'
      }
      steps {
        nodejs(nodeJSInstallationName: 'nodejs 8.9.4') {
          sh 'echo "Build application..."'
          sh 'npm run build'
          sh 'echo "Build application successfully."'
          sh 'ls -al'
        }
        script {
          stash includes: 'build/', name: 'build'
        }
      }
    }

    stage ('Create docker images') {
      when {
        branch 'develop'
      }
      steps {
        script {
          unstash 'build'
        }
        sh '''
          ls -al
          echo "Starting to build docker image for dev env"
          docker build -t pick-color:v1-dev -f docker/Dockerfile.no_build .
          docker push 
        '''
      }
    }
    stage ('Create docker images') {
      when {
        branch 'release'
      }
      steps {
        script {
          unstash 'build'
        }
        sh '''
          ls -al
          echo "Starting to build docker image, prepare for release"
          docker build -t pick-color:v1-release -f docker/Dockerfile.no_build .
          docker push 
        '''
      }
    }
  }
}
